# Generated by Django 4.0.2 on 2022-03-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComingFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.gender')),
            ],
        ),
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_time', models.TimeField()),
                ('passenger_code', models.CharField(max_length=30)),
                ('coming_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.comingfrom')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.destination')),
                ('flight_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flightcategory')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.meal')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.passenger')),
            ],
        ),
    ]
